# depends on: apt install ssl-cert
# install: sudo ln -s ~/klipper-config/nginx/https_redirect.conf /etc/nginx/conf.d/https_redirect.conf && sudo nginx -t && sudo systemctl reload nginx
server {
    listen 443 ssl;
    ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
    return 301 http://$host$request_uri;
}
